# Generated by Django 5.0.7 on 2024-08-05 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Наименование категории",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="Наименование задачи"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание задачи")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("N", "New"),
                            ("I", "In Progress"),
                            ("P", "Pending"),
                            ("B", "Blocked"),
                            ("D", "Done"),
                        ],
                        max_length=50,
                        verbose_name="Тип задачи",
                    ),
                ),
                ("deadline", models.DateField(verbose_name="Срок выполнения")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время начала выполнения"
                    ),
                ),
                ("categories", models.ManyToManyField(to="homeworks8.category")),
            ],
        ),
        migrations.CreateModel(
            name="SubTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="Наименование подзадачи"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание подзадачи")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("N", "New"),
                            ("I", "In Progress"),
                            ("P", "Pending"),
                            ("B", "Blocked"),
                            ("D", "Done"),
                        ],
                        max_length=50,
                        verbose_name="Тип подзадачи",
                    ),
                ),
                ("deadline", models.DateField(verbose_name="Срок выполнения")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время начала выполнения"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homeworks8.task",
                        verbose_name="Основная задача",
                    ),
                ),
            ],
        ),
    ]
