# Generated by Django 5.0.7 on 2024-08-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homeworks8", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subtask",
            options={"ordering": ["-created_at"], "verbose_name": "Subtask"},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-created_at"], "verbose_name": "Task"},
        ),
        migrations.AlterField(
            model_name="subtask",
            name="title",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Наименование подзадачи"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Наименование задачи"
            ),
        ),
        migrations.AlterModelTable(
            name="subtask",
            table="task_manager_subtask",
        ),
        migrations.AlterModelTable(
            name="task",
            table="task_manager_task",
        ),
    ]
